env:
  node: true

extends:
  - 'airbnb-base'

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - fp

rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
